- name: Check and save certificate expiry date
  hosts: all
  tasks:
    - name: Get the certificate from the host
      community.crypto.get_certificate:
        host: "apache-demo.wesentra.com"
        port: 443
        asn1_base64: false  # Explicitly set the value to avoid deprecation warning
      delegate_to: localhost
      register: cert_info
      ignore_errors: yes

    - name: Check if certificate retrieval was successful
      ansible.builtin.fail:
        msg: "Failed to get certificate from apache-demo.wesentra.com:443"
      when: cert_info is not defined or cert_info.not_after is not defined

    - name: Save the certificate expiry date as a fact
      set_fact:
        cert_expiry_date: "{{ cert_info.not_after }}"
      when: cert_info is defined and cert_info.not_after is defined

    - name: Display the saved expiry date
      ansible.builtin.debug:
        msg: "The certificate expires on {{ cert_expiry_date }}"
      when: cert_info is defined and cert_info.not_after is defined