- name: Fetch file fromn remote host
  hosts: all
  gather_facts: yes
  become: true

  Tasks:
  
  - name: Copy the existing Cert to temporary file on localhost
    fetch:
      src: /etc/ssl/certs/ansible-demo.crt
      dest: /home/azureuser/tmp/ansible-demo.pem
      fail_on_missing: false
        