---
- name: Reissue Certificate
  hosts: all
  gather_facts: yes
  become: true
  become_method: sudo
  
  

  vars:
    network:
      api_username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      api_password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

    
  tasks:
 
  - name: Create certificate private key on the server.
    openssl_privatekey:
      path: /etc/ssl/private/apache-demo.key
      type: RSA
      size: 2048
    become_user: root

  - name: Delete existing CSR
    ansible.builtin.file:
      path: /etc/ssl/csr/csr.pem
      state: absent

  - name: Backup existing Certificate if it exists
    stat: /etc/ssl/certs/apache-demo.crt
    register: st
    copy:
      src: /etc/ssl/certs/apache-demo.crt
      dest: /tmp/apache-demo.pem.{{ ansible_date_time.iso8601 }}
      remote_src: yes
      ignore_errors: true
    when: st.stat.exists

  #- name: Copy the existing Cert to temporary file on localhost
  #  fetch:
   #   src: /etc/ssl/certs/ansible-demo.crt
    #  dest: /home/azureuser/tmp/ansible-demo.pem
     # fail_on_missing: false
        

  - name: Create certificate signing request on the server
    openssl_csr:
      path: /etc/ssl/crs/csr.pem
      privatekey_path: /home/azureuser/tmp/ansible-demo.key
 #     privatekey_passphrase: 'ansible'
      digest: sha256
      common_name: ansible-demo.wesentra.com
      organization_name: Wesentra Oy
      organizational_unit_name: Verification
      country_name: FI
      state_or_province_name: Keski-Suomi

  #- name: Copy the CSR to temporary file on localhost
   # fetch:
    #  src: /home/azureuser/tmp/csr.pem
     # dest: /home/azureuser/tmp/csr.pem
      #flat: true
      #fail_on_missing: false
    #become: true
    

  - name: If there is no certificate present in path, request a new certificate
          of type PRIVATE_SSL. Otherwise, if there is an Entrust managed certificate
          in path and it is within 365 days of expiration, request a REISSUE of that
          certificate.
          
    ecs_certificate:
      path: /etc/ssl/certs/ansible-demo.crt
      csr: /etc/ssl/csr/csr.pem
      cert_type: STANDARD_SSL
  #    cert_expiry: '2020-08-20'
      request_type: reissue
      remaining_days: 365
      requester_name: Harry Ansible
      requester_email: harry@wesentra.com
      requester_phone: 555-555-5555
      entrust_api_user: '{{ api_user }}'
      entrust_api_key: '{{ api_pass }}'
      entrust_api_client_cert_path: '{{ lookup("env", "API_CLIENT_CERTIFICATE") }}'
      entrust_api_client_cert_key_path: '{{ lookup("env", "API_PRIVATE_KEY") }}'
       

  #- name: Copy private key to Private key folder
    #copy:
     # src: /home/azureuser/tmp/ansible-demo.key
      #dest: /etc/ssl/private/ansible-demo.key
      #remote_src: yes

# - name: Copy certificate to site certificate store
 #   copy:
  #    src: /home/ansibleuser/tmp/ansible-demo.pem
   #   dest: /etc/ssl/certs/ansible-demo.crt

  - name: restart Apache
    service:
      name: httpd
      state: restarted
...
