---
- name: Reissue Certificate
  hosts: all
  gather_facts: yes
  become: true
  

  vars:
    network:
      api_username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      api_password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

  
      api_certificate: '{{ lookup("env", "API_CLIENT_CERTIFICATE") }}'
      api_private_key: '{{ lookup("env", "API_PRIVATE_KEY") }}'

  tasks:
 
  - name: Create certificate private key on the server.
    openssl_privatekey:
      path: /home/azureuser/tmp/ansible-demo.key
      type: RSA
      size: 2048
      
  - name: Delete existing CSR
    ansible.builtin.file:
      path: /home/azureuser/tmp/csr.pem
      state: absent

  - name: Backup existing Certificate
    copy:
      src: /etc/ssl/certs/ansible-demo.crt
      dest: /home/azureuser/ansibledemo_backups/cert.pem.{{ ansible_date_time.iso8601 }}
      remote_src: yes

  - name: Copy the existing Cert to temporary file on localhost
    fetch:
      src: /etc/ssl/certs/ansible-demo.crt
      dest: /home/azureuser/tmp/cert.pem
      flat: true
      fail_on_missing: false

  - name: Create certificate signing request on the server
    openssl_csr:
      path: /home/azureuser/tmp/csr.pem
      privatekey_path: /home/azureuser/tmp/ansible-demo.key
 #     privatekey_passphrase: 'ansible'
      digest: sha256
      common_name: ansible-demo.wesentra.com
      organization_name: Wesentra Oy
      organizational_unit_name: Verification
      country_name: FI
      state_or_province_name: Keski-Suomi

  - name: Copy the CSR to temporary file on localhost
    fetch:
     src: /home/azureuser/tmp/csr.pem
     flat: true
     fail_on_missing: false

  - name: If there is no certificate present in path, request a new certificate
          of type PRIVATE_SSL. Otherwise, if there is an Entrust managed certificate
          in path and it is within 365 days of expiration, request a REISSUE of that
          certificate.
    become_method: sudo
    become_exe: 'sudo -p "Password: " su -'
    ecs_certificate:
      path: /home/azureuser/tmp/csr.pem
      csr: /home/azureuser/tmp/csr.pem
      cert_type: PRIVATE_SSL
  #    cert_expiry: '2020-08-20'
      request_type: reissue
      remaining_days: 365
      requester_name: Harry Ansible
      requester_email: harry@wesentra.com
      requester_phone: 555-555-5555
      entrust_api_user: '{{ api_user }}'
      entrust_api_key: '{{ api_pass }}'
      entrust_api_client_cert_path: /home/azureuser/cagw_cert.pem
      entrust_api_client_cert_key_path: /home/azureuser/cagw_key.key
    delegate_to: localhost
    

  - name: Copy private key to Private key folder
    copy:
      src: /home/azureuser/tmp/ansible-demo.key
      dest: /etc/ssl/private/ansible-demo.key
      remote_src: yes

 # - name: Copy certificate to Apache folder
 #   copy:
 #    src: /home/weseroot/tmp/cert.pem
 #    dest: /etc/apache2/ssl/ca.crt

  - name: restart Ngninx
    service:
      name: Ngninx
      state: restarted
...
