---
- name: Print Enviromental variables 
  hosts: all
  become_user: root

  vars:
    pem: ".pem"
    key: ".key"

  tasks:
   - debug:
      msg:
      - "api_cert: {{ lookup('env', 'API_CLIENT_CERTIFICATE') }}{{ pem }}"
      - "private_key: {{ lookup('env', 'API_PRIVATE_KEY') }}{{ key }}"
  
