---
- name: Print Enviromental variables 
  hosts: all
  become_user: root
  debug:
    msg:
    - "api_cert: {{ lookup('env', 'PUBLIC_CERT') }}"
    - "private_key: {{ lookup('env', 'PRIVATE_KEY') }}"
  delegate_to: local  
