---
- name: Print Enviromental variables 
  hosts: all
  become_user: root

  vars:
    pem: ".pem"
    key: ".key"

  tasks:
   - command:
      cmd: cat "{{ lookup('env', 'API_CLIENT_CERTIFICATE') }}{{ pem }}"
     register: out 

   - debug: 
      msg: "{{ out.stdout }}"

  
