---
- name: Print Enviromental variables 
  hosts: localhost 
  become_user: root

  tasks:
   - debug:
      msg:
      - "api_cert: {{ lookup('env', 'API_CLIENT_CERTIFICATE') }}"
      - "private_key: {{ lookup('env', 'API_PRIVATE_KEY') }}"
  
