---
- name: Print Enviromental variables 
  hosts: all
  become_user: root

  ansible.builtin.debug:
    msg:
    - "api_cert: {{ lookup('env', 'PUBLIC_CERT') }}"
    - "private_key: {{ lookup('env', 'PRIVATE_KEY') }}"
   
