---
- name: Print Enviromental variables 
  hosts: localhost 
  become_user: root

  tasks:
   - debug:
      msg:
      - "api_cert: {{ lookup('env', 'PUBLIC_CERT') }}"
      - "private_key: {{ lookup('env', 'PRIVATE_KEY') }}"
  delegate_to: localhost   
